## usage: plotCorrelation -in matrix.gz -c spearman -p heatmap -o plot.png
## help: plotCorrelation -h / plotCorrelation --help
## 
## Tool for the analysis and visualization of sample correlations based on the output of multiBamSummary or
## multiBigwigSummary. Pearson or Spearman methods are available to compute correlation
## coefficients. Results can be saved as multiple
## scatter plots depicting the pairwise correlations or as a clustered heatmap,
## where the colors represent the correlation coefficients and the clusters are constructed using complete linkage.
## Optionally, the values can be saved as tables, too.
## 
## detailed help:
## 
##   plotCorrelation -h
## 
## optional arguments:
##   -h, --help            show this help message and exit
## 
## Required arguments:
##   --corData FILE, -in FILE
##                         Compressed matrix of values generated by multiBigwigSummary or multiBamSummary
##   --corMethod {spearman,pearson}, -c {spearman,pearson}
##                         Correlation method.
##   --whatToPlot {heatmap,scatterplot}, -p {heatmap,scatterplot}
##                         Choose between a heatmap or pairwise scatter plots
## 
## Optional arguments:
##   --plotFile FILE, -o FILE
##                         File to save the heatmap to. The file extension determines the format, so heatmap.pdf will save the heatmap in PDF format. The available formats are: .png, .eps,
##                         .pdf and .svg.
##   --skipZeros           By setting this option, genomic regions that have zero or missing (nan) values in all samples are excluded.
##   --labels sample1 sample2 [sample1 sample2 ...], -l sample1 sample2 [sample1 sample2 ...]
##                         User defined labels instead of default labels from file names. Multiple labels have to be separated by spaces, e.g. --labels sample1 sample2 sample3
##   --plotTitle PLOTTITLE, -T PLOTTITLE
##                         Title of the plot, to be printed on top of the generated image. Leave blank for no title. (Default: )
##   --plotFileFormat FILETYPE
##                         Image format type. If given, this option overrides the image format based on the plotFile ending. The available options are: png, eps, pdf and svg.
##   --removeOutliers      If set, bins with very large counts are removed. Bins with abnormally high reads counts artificially increase pearson correlation; that's why, multiBamSummary
##                         tries to remove outliers using the median absolute deviation (MAD) method applying a threshold of 200 to only consider extremely large deviations from the
##                         median. The ENCODE blacklist page (https://sites.google.com/site/anshulkundaje/projects/blacklists) contains useful information about regions with unusually high
##                         countsthat may be worth removing.
##   --version             show program's version number and exit
## 
## Output optional options:
##   --outFileCorMatrix FILE
##                         Save matrix with pairwise correlation values to a tab-separated file.
## 
## Heatmap options:
##   --plotHeight PLOTHEIGHT
##                         Plot height in cm. (Default: 9.5)
##   --plotWidth PLOTWIDTH
##                         Plot width in cm. The minimum value is 1 cm. (Default: 11)
##   --zMin ZMIN, -min ZMIN
##                         Minimum value for the heatmap intensities. If not specified, the value is set automatically
##   --zMax ZMAX, -max ZMAX
##                         Maximum value for the heatmap intensities.If not specified, the value is set automatically
##   --colorMap            Color map to use for the heatmap. Available values can be seen here: http://matplotlib.org/examples/color/colormaps_reference.html
##   --plotNumbers         If set, then the correlation number is plotted on top of the heatmap. This option is only valid when plotting a heatmap.
## 
## Scatter plot options:
##   --xRange XRANGE XRANGE
##                         The X axis range. The default scales these such that the full range of dots is displayed.
##   --yRange YRANGE YRANGE
##                         The Y axis range. The default scales these such that the full range of dots is displayed.
##   --log1p               Plot the natural log of the scatter plot after adding 1. Note that this is ONLY for plotting, the correlation is unaffected.
## 
## example usages:
## plotCorrelation -in results_file --whatToPlot heatmap --corMethod pearson -o heatmap.png
## 
##  


plotCorrelation <- function(..., nthreads=1, params, condaenv) 
{ 
}

