## usage: plotPCA -in coverage.npz -o pca.png
## help: plotPCA -h / plotPCA --help
## 
## Tool for generating a principal component analysis (PCA)
## plot from multiBamSummary or multiBigwigSummary output. By default, the loadings for each sample in each principal component is plotted. If the data is transposed, the projections of each sample on the requested principal components is plotted instead.
## 
## Detailed help:
## 
##   plotPCA -h
## 
## optional arguments:
##   -h, --help            show this help message and exit
##   --transpose           Perform the PCA on the transposed matrix, (i.e., on the matrix where rows are samples and columns are bins/features. This then matches what is typically done in
##                         R.
##   --rowCenter           When specified, each row (bin, gene, etc.) in the matrix is centered at 0 before the PCA is computed. This is useful only if you have a strong bin/gene/etc.
##                         correlation and the resulting principal component has samples stacked vertically. This option is not applicable if --transpose is specified.
## 
## Required arguments:
##   --corData FILE, -in FILE
##                         Coverage file (generated by multiBamSummary or multiBigwigSummary)
## 
## Optional arguments:
##   --plotFile FILE, -o FILE
##                         File name to save the plot to. The extension determines the file format. For example: pca.pdf will save the PCA plot in PDF format. The available options are:
##                         .png, .eps, .pdf and .svg. If this option is omitted, then you MUST specify --outFileNameData
##   --labels sample1 sample2 [sample1 sample2 ...], -l sample1 sample2 [sample1 sample2 ...]
##                         User defined labels instead of default labels from file names. Multiple labels have to be separated by spaces, e.g. --labels sample1 sample2 sample3
##   --plotTitle PLOTTITLE, -T PLOTTITLE
##                         Title of the plot, to be printed on top of the generated image. Leave blank for no title. (Default: )
##   --plotFileFormat FILETYPE
##                         Image format type. If given, this option overrides the image format based on the plotFile ending. The available options are: png, eps, pdf, plotly and svg.
##   --plotHeight PLOTHEIGHT
##                         Plot height in cm. (Default: 10)
##   --plotWidth PLOTWIDTH
##                         Plot width in cm. The minimum value is 1 cm. (Default: 10)
##   --outFileNameData file.tab
##                         File name to which the data underlying the plot should be saved, such as myPCA.tab. For untransposed data, this is the loading per-sample and PC as well as the
##                         eigenvalues. For transposed data, this is the rotation per-sample and PC and the eigenvalues. The projections are truncated to the number of eigenvalues for
##                         transposed data.
##   --ntop NTOP           Use only the top N most variable rows in the original matrix. Specifying 0 will result in all rows being used. If the matrix is to be transposed, rows with 0
##                         variance are always excluded, even if a values of 0 is specified. The default is 1000. (Default: 1000)
##   --PCs PCS PCS         The principal components to plot. If specified, you must provide two different integers, greater than zero, separated by a space. An example (and the default) is
##                         "1 2". (Default: [1, 2])
##   --log2                log2 transform the datapoints prior to computing the PCA. Note that 0.01 is added to all values to prevent 0 values from becoming -infinity. Using this option
##                         with input that contains negative values will result in an error.
##   --colors COLORS [COLORS ...]
##                         A list of colors for the symbols. Color names and html hex string (e.g., #eeff22) are accepted. The color names should be space separated. For example, --colors
##                         red blue green. If not specified, the symbols will be given automatic colors.
##   --markers MARKERS [MARKERS ...]
##                         A list of markers for the symbols. (e.g., '<','>','o') are accepted. The marker values should be space separated. For example, --markers 's' 'o' 's' 'o'. If not
##                         specified, the symbols will be given automatic shapes.
##   --version             show program's version number and exit
## 
## example usages:
## plotPCA -in coverages.npz -o pca.png
## 
##  


plotPCA <- function(..., nthreads=1, params, condaenv) 
{ 
}

